import type { AiFlagDef, SchemaDef } from './types';

export const GA_DIVORCE_CUSTODY_V1: SchemaDef = {
  version: 'v1.0',
  sections: [
    {
      id: 'matter_metadata',
      title: 'MATTER METADATA (SYSTEM + CLIENT)',
      fields: [
        {
          key: 'matter_type',
          type: 'enum',
          required: true,
          notes: 'divorce, custody, legitimation, modification',
          enumValues: ['divorce', 'custody', 'legitimation', 'modification'],
        },
        {
          key: 'urgency_level',
          type: 'enum',
          required: true,
          notes: 'routine, urgent, emergency',
          enumValues: ['routine', 'urgent', 'emergency'],
        },
        {
          key: 'intake_channel',
          type: 'enum',
          required: true,
          notes: 'web, referral, phone',
          enumValues: ['web', 'referral', 'phone'],
        },
        {
          key: 'language_preference',
          type: 'enum',
          required: false,
          notes: 'future multilingual support',
          enumValues: ['english', 'spanish', 'other', 'unknown', 'prefer_not_to_say'],
        },
        {
          key: 'date_of_intake',
          type: 'date',
          required: true,
          notes: 'system generated',
        },
      ],
    },
    {
      id: 'client_identity',
      title: 'CLIENT IDENTITY',
      fields: [
        { key: 'client_first_name', type: 'text', required: true },
        { key: 'client_last_name', type: 'text', required: true },
        { key: 'client_dob', type: 'date', required: true },
        { key: 'client_phone', type: 'text', required: true },
        { key: 'client_email', type: 'text', required: true },
        { key: 'client_address', type: 'structured', required: true, notes: 'structured address' },
        {
          key: 'client_county',
          type: 'enum',
          required: true,
          notes: 'CSV-derived (docs/ga_counties.csv)',
        },
        {
          key: 'citizenship_status',
          type: 'enum',
          required: false,
          enumValues: [
            'us_citizen',
            'lawful_permanent_resident',
            'nonimmigrant_visa_holder',
            'undocumented',
            'dual_citizen',
            'unknown',
            'prefer_not_to_say',
          ],
        },
        { key: 'military_status', type: 'boolean', required: false },
      ],
    },
    {
      id: 'opposing_party',
      title: 'OPPOSING PARTY (SPOUSE / OTHER PARENT)',
      fields: [
        { key: 'opposing_name', type: 'text', required: true },
        { key: 'opposing_address_known', type: 'boolean', required: true },
        {
          key: 'opposing_last_known_address',
          type: 'structured',
          required: true,
          notes: 'structured address; required if opposing_address_known',
        },
        { key: 'service_concerns', type: 'boolean', required: false },
        {
          key: 'opposing_employment_status',
          type: 'enum',
          required: false,
          enumValues: [
            'employed_full_time',
            'employed_part_time',
            'self_employed',
            'unemployed',
            'student',
            'retired',
            'disabled',
            'unknown',
          ],
        },
      ],
    },
    {
      id: 'marriage_details',
      title: 'MARRIAGE DETAILS',
      fields: [
        { key: 'date_of_marriage', type: 'date', required: true },
        { key: 'place_of_marriage', type: 'text', required: true },
        { key: 'date_of_separation', type: 'date', required: true, notes: 'required if separated' },
        { key: 'currently_cohabitating', type: 'boolean', required: true },
        { key: 'marriage_certificate_available', type: 'boolean', required: false },
      ],
    },
    {
      id: 'separation_grounds',
      title: 'SEPARATION & GROUNDS (GEORGIA)',
      fields: [
        {
          key: 'grounds_for_divorce',
          type: 'enum',
          required: true,
          enumValues: [
            'no_fault',
            'adultery',
            'desertion',
            'cruel_treatment',
            'habitual_drug_use',
            'mental_incapacity',
            'impotence',
            'pregnancy_by_another',
            'incest',
            'conviction_of_felony',
          ],
        },
        {
          key: 'fault_allegations',
          type: 'multiselect',
          required: false,
          enumValues: [
            'adultery',
            'desertion',
            'cruel_treatment',
            'habitual_drug_use',
            'mental_incapacity',
            'impotence',
            'pregnancy_by_another',
            'incest',
            'conviction_of_felony',
          ],
        },
        { key: 'reconciliation_attempted', type: 'boolean', required: false },
      ],
    },
    {
      id: 'child_object',
      title: 'CHILD OBJECT (REPEATABLE)',
      fields: [
        { key: 'child_full_name', type: 'text', required: true },
        { key: 'child_dob', type: 'date', required: true },
        {
          key: 'child_current_residence',
          type: 'enum',
          required: true,
          enumValues: ['with_client', 'with_opposing', 'shared', 'third_party', 'other', 'unknown'],
        },
        {
          key: 'biological_relation',
          type: 'enum',
          required: true,
          enumValues: ['client', 'opposing', 'both', 'neither', 'unknown'],
        },
        { key: 'special_needs', type: 'boolean', required: false },
      ],
    },
    {
      id: 'children_custody',
      title: 'CHILDREN & CUSTODY (CUSTODY SETTINGS)',
      fields: [
        {
          key: 'custody_type_requested',
          type: 'enum',
          required: true,
          enumValues: ['legal_custody', 'physical_custody', 'joint_custody', 'sole_custody'],
        },
        { key: 'parenting_plan_exists', type: 'boolean', required: true },
        { key: 'modification_existing_order', type: 'boolean', required: false, notes: 'modification only' },
        { key: 'current_parenting_schedule', type: 'text', required: false },
        { key: 'school_district', type: 'text', required: false },
      ],
    },
    {
      id: 'asset_object',
      title: 'ASSET OBJECT (REPEATABLE)',
      fields: [
        {
          key: 'asset_type',
          type: 'enum',
          required: true,
          enumValues: [
            'real_estate',
            'vehicle',
            'bank_account',
            'retirement_account',
            'investment_account',
            'business_interest',
            'personal_property',
            'other',
          ],
        },
        {
          key: 'ownership',
          type: 'enum',
          required: true,
          enumValues: ['sole_client', 'sole_opposing', 'joint', 'third_party', 'unknown'],
        },
        { key: 'estimated_value', type: 'number', required: true },
        {
          key: 'title_holder',
          type: 'enum',
          required: true,
          enumValues: ['client', 'opposing', 'both', 'third_party', 'unknown'],
        },
        { key: 'acquired_pre_marriage', type: 'boolean', required: true },
      ],
    },
    {
      id: 'income_support',
      title: 'INCOME & SUPPORT',
      fields: [
        { key: 'client_income_monthly', type: 'number', required: true },
        { key: 'opposing_income_known', type: 'boolean', required: true },
        {
          key: 'support_requested',
          type: 'enum',
          required: true,
          enumValues: ['child_support', 'spousal_support', 'both'],
        },
        {
          key: 'child_support_estimate',
          type: 'number',
          required: false,
          isSystem: true,
          notes: 'system-only',
        },
        { key: 'alimony_requested', type: 'boolean', required: false },
      ],
    },
    {
      id: 'debt_object',
      title: 'DEBT OBJECT (REPEATABLE)',
      fields: [
        {
          key: 'debt_type',
          type: 'enum',
          required: true,
          enumValues: [
            'credit_card',
            'student_loan',
            'auto_loan',
            'mortgage',
            'medical_debt',
            'tax_debt',
            'personal_loan',
            'other',
          ],
        },
        { key: 'amount', type: 'number', required: true },
        {
          key: 'responsible_party',
          type: 'enum',
          required: true,
          enumValues: ['client', 'opposing', 'both', 'third_party', 'unknown'],
        },
        { key: 'incurred_during_marriage', type: 'boolean', required: true },
      ],
    },
    {
      id: 'domestic_violence_risk',
      title: 'DOMESTIC VIOLENCE / RISK',
      fields: [
        { key: 'dv_present', type: 'boolean', required: true },
        { key: 'protective_order_exists', type: 'boolean', required: true, notes: 'required if dv_present' },
        { key: 'immediate_safety_concerns', type: 'boolean', required: true },
        { key: 'children_exposed', type: 'boolean', required: false },
      ],
    },
    {
      id: 'jurisdiction_venue',
      title: 'JURISDICTION & VENUE',
      fields: [
        {
          key: 'county_of_filing',
          type: 'enum',
          required: true,
          notes: 'CSV-derived (docs/ga_counties.csv)',
        },
        { key: 'residency_duration_months', type: 'number', required: true },
        { key: 'opposing_resides_in_ga', type: 'boolean', required: false },
        { key: 'venue_confirmed', type: 'boolean', required: false, isSystem: true },
      ],
    },
    {
      id: 'prior_legal_actions',
      title: 'PRIOR LEGAL ACTIONS',
      fields: [
        { key: 'prior_divorce_filings', type: 'boolean', required: true },
        { key: 'prior_custody_orders', type: 'boolean', required: true },
        { key: 'case_numbers', type: 'text', required: false },
        { key: 'existing_attorney', type: 'boolean', required: true },
      ],
    },
    {
      id: 'desired_outcomes',
      title: 'DESIRED OUTCOMES',
      fields: [
        {
          key: 'primary_goal',
          type: 'enum',
          required: true,
          enumValues: [
            'divorce_finalization',
            'custody_determination',
            'custody_modification',
            'support_establishment',
            'support_modification',
            'property_division',
            'protective_relief',
            'legal_guidance',
            'other',
          ],
        },
        {
          key: 'settlement_preference',
          type: 'enum',
          required: true,
          enumValues: [
            'strongly_prefer_settlement',
            'prefer_settlement',
            'open_to_either',
            'prefer_litigation',
            'strongly_prefer_litigation',
            'unsure',
          ],
        },
        {
          key: 'litigation_tolerance',
          type: 'enum',
          required: true,
          enumValues: ['low', 'moderate', 'high', 'unknown'],
        },
        { key: 'non_negotiables', type: 'text', required: false },
      ],
    },
    {
      id: 'evidence_documents',
      title: 'EVIDENCE & DOCUMENTS',
      fields: [
        {
          key: 'document_type',
          type: 'enum',
          required: false,
          enumValues: [
            'pay_stub',
            'tax_return',
            'bank_statement',
            'financial_statement',
            'real_estate_document',
            'vehicle_title',
            'retirement_statement',
            'business_record',
            'text_message',
            'email',
            'photo',
            'video',
            'police_report',
            'court_order',
            'protective_order',
            'medical_record',
            'school_record',
            'other',
          ],
        },
        { key: 'uploaded', type: 'boolean', required: false },
        {
          key: 'missing_required_docs',
          type: 'list',
          required: false,
          isSystem: true,
          notes: 'system-only',
        },
      ],
    },
  ],
};

export const GA_DIVORCE_CUSTODY_V1_AI_FLAGS: AiFlagDef[] = [
  { key: 'jurisdiction_risk', trigger: 'Residency / venue mismatch' },
  { key: 'dv_risk', trigger: 'DV indicated + weapons present' },
  { key: 'custody_complexity', trigger: 'Multiple children + special needs' },
  { key: 'asset_complexity', trigger: 'Business / high-value assets detected' },
  { key: 'support_complexity', trigger: 'Support requested + income disparity' },
  { key: 'missing_required', trigger: 'Required fields missing at submission' },
];
